// <auto-generated />
namespace Hotel_Reservation_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Price : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Price));
        
        string IMigrationMetadata.Id
        {
            get { return "202111080038346_Price"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
